### ISSUE TITLE
相机无法打开

### ISSUE THREAD

**Issue by UC10D** [1030310877/Eyer#1]
if (ActivityCompat.checkSelfPermission(context, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) {
                    if (cameraOpenCallBack != null) {
                        cameraOpenCallBack.onFailed();
                    }
                    return;
                }

  cameraOpenCallBack.onFailed();

**Comment by joechan-cq** [comment]
请问具体的Android版本，以及是否有错误日志？

**Comment by UC10D** [comment]
MI 3  android 6.0.1MMB29M   不是崩溃，回调 cameraOpenCallBack.onFailed();

**Comment by UC10D** [comment]
MI 3  android 6.0.1MMB29M   不是崩溃，回调 cameraOpenCallBack.onFailed();

**Comment by joechan-cq** [comment]
因为代码中没写6.0的主动的权限请求，所以相机没有打开，可以在应用设置中把相机权限给了后就可以正常打开相机了。我后续会把权限请求加上。

**Comment by UC10D** [comment]
我看了 相册的权限是打开的，我在看看吧

**Comment by joechan-cq** [comment]
恩，我这专门找了个MI5的android6.0的手机测试了一下，权限打开后可以的。不是相册的权限，是相机的权限

**Comment by UC10D** [comment]
恩，谢啦
